/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movieticketorder.admin;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import movieticketorder.object.Movie;
import java.sql.*;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Admin
 */
public class EditMovie extends javax.swing.JFrame {
    /**
     * Creates new form AddMovie
     */
    Movie movie = new Movie();
    String URL = "jdbc:sqlserver://HiepPC\\SQLEXPRESS:1433;"
                    + "username=sa;password=123456;databasename=movieTicketBooking;encrypt=false";
    public EditMovie() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(null);
        this.setTitle("Edit Movie");
    }
    public EditMovie(int MovieID) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(null);
        this.setTitle("Edit Movie");
        movie.setMovieID(MovieID);
        Display(movie.getMovieID());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public ImageIcon ResizeImage(JLabel j,String ImagePath){
        // resize image fit to jlabel 
        ImageIcon MyImage = new ImageIcon(getClass().getResource("/resources/movies/poster/" + ImagePath));
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(j.getWidth(), j.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    public void Display(int id){
        try{
            Connection connect = DriverManager.getConnection(URL);
            String sql = "SELECT name, autor, description, time, poster, trailer FROM movie WHERE movieID=?";
            PreparedStatement ps = connect.prepareStatement(sql);
            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                movie.setMovieName(rs.getString("name"));
                movie.setMovieAutor(rs.getString("autor"));
                movie.setMovieDescription(rs.getString("description"));
                movie.setMovieTime(rs.getInt("time"));
                movie.setMoviePoster(rs.getString("poster"));
                movie.setMovieTrailer(rs.getString("trailer"));
            }
            jTextMovieName.setText(movie.getMovieName());
            jTextAutor.setText(movie.getMovieAutor());
            jTextArea1.setText(movie.getMovieDescription());
            jTextTime.setText(String.valueOf(movie.getMovieTime()));
            jLabelPoster.setIcon(ResizeImage(jLabelPoster,movie.getMoviePoster()));

            System.out.println("Poster: " + movie.getMoviePoster());
            System.out.println("Trailer: " + movie.getMovieTrailer());
            connect.close();
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }
    public boolean UpdateMovie(){
        int movie_ID = movie.getMovieID();
        movie.setMovieName(jTextMovieName.getText());
        movie.setMovieAutor(jTextAutor.getText());
        movie.setMovieDescription(jTextArea1.getText());
        movie.setMovieTime(Integer.valueOf(jTextTime.getText()));
                
        boolean flag = true;
        if(movie.getMovieName().isEmpty()){
            flag = false;
            ImageIcon icon = new ImageIcon(getClass().getResource("/resources/icons/warning.png"));
            JOptionPane.showMessageDialog(this, "Movie name is empty."," Warning!",JOptionPane.INFORMATION_MESSAGE,icon);
        }else if(movie.getMovieAutor().isEmpty()){
            flag = false;
            ImageIcon icon = new ImageIcon(getClass().getResource("/resources/icons/warning.png"));
            JOptionPane.showMessageDialog(this, "Movie autor is empty."," Warning!",JOptionPane.INFORMATION_MESSAGE,icon);
        }else if(movie.getMovieDescription().isEmpty()){
            flag = false;
            ImageIcon icon = new ImageIcon(getClass().getResource("/resources/icons/warning.png"));
            JOptionPane.showMessageDialog(this, "Description is empty."," Warning!",JOptionPane.INFORMATION_MESSAGE,icon);
        }else if(movie.getMovieTime() <= 0){
            flag = false;
            ImageIcon icon = new ImageIcon(getClass().getResource("/resources/icons/warning.png"));
            JOptionPane.showMessageDialog(this, "Time isn't valid."," Warning!",JOptionPane.INFORMATION_MESSAGE,icon);
        }else if(movie.getMoviePoster().isEmpty()){
            flag = false;
            ImageIcon icon = new ImageIcon(getClass().getResource("/resources/icons/warning.png"));
            JOptionPane.showMessageDialog(this, "Image hasn't been upload."," Warning!",JOptionPane.INFORMATION_MESSAGE,icon);
        }else if(movie.getMovieTrailer().isEmpty()){
            flag = false;
            ImageIcon icon = new ImageIcon(getClass().getResource("/resources/icons/warning.png"));
            JOptionPane.showMessageDialog(this, "Video hasn't been upload."," Warning!",JOptionPane.INFORMATION_MESSAGE,icon);
        }

        if(flag){
            try{
                Connection connect = DriverManager.getConnection(URL);
                String sql = "UPDATE movie SET name=?,autor=?,description=?,time=?,poster=?,trailer=? WHERE movieID=?";
                PreparedStatement ps = connect.prepareStatement(sql);
                ps = connect.prepareStatement(sql);
                ps.setString(1,movie.getMovieName());
                ps.setString(2,movie.getMovieAutor());
                ps.setString(3,movie.getMovieDescription());
                ps.setInt(4, movie.getMovieTime());
                ps.setString(5, movie.getMoviePoster());
                ps.setString(6, movie.getMovieTrailer());
                ps.setInt(7, movie_ID);

                ps.executeUpdate();
                connect.close();
                return flag;
            }catch(SQLException ex){
                flag = false;
                ex.printStackTrace();
            }
        }
        return flag;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelPoster = new javax.swing.JLabel();
        jButtonPoster = new javax.swing.JButton();
        jTextMovieName = new javax.swing.JTextField();
        jTextAutor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonAddTrailer = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextTime = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Movie Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Autor");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Description");

        jLabelPoster.setBackground(new java.awt.Color(255, 0, 0));
        jLabelPoster.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabelPoster.setForeground(new java.awt.Color(0, 0, 0));
        jLabelPoster.setText("     Poster");

        jButtonPoster.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPoster.setForeground(new java.awt.Color(0, 0, 0));
        jButtonPoster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/Movies-32.png"))); // NOI18N
        jButtonPoster.setText("Poster");
        jButtonPoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPosterActionPerformed(evt);
            }
        });

        jTextMovieName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextMovieName.setForeground(new java.awt.Color(0, 0, 0));
        jTextMovieName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMovieNameActionPerformed(evt);
            }
        });

        jTextAutor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextAutor.setForeground(new java.awt.Color(0, 0, 0));

        jTextArea1.setColumns(15);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setTabSize(4);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonAddTrailer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAddTrailer.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAddTrailer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/Treetog-I-Videos.32.png"))); // NOI18N
        jButtonAddTrailer.setText("Trailer");
        jButtonAddTrailer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTrailerActionPerformed(evt);
            }
        });

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/Home-48.png"))); // NOI18N
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(0, 0, 0));
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/Update-32.png"))); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.setMaximumSize(new java.awt.Dimension(151, 40));
        jButtonUpdate.setMinimumSize(new java.awt.Dimension(151, 40));
        jButtonUpdate.setPreferredSize(new java.awt.Dimension(151, 40));
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/Babasse-Old-School-Old-videos.128.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/Yohproject-Crayon-Cute-Movies.48.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Time");

        jTextTime.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextTime.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/Itzikgur-My-Seven-Movies-Films.48.png"))); // NOI18N
        jLabel9.setText("jLabel7");

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 51, 255));
        jLabel10.setText("Edit Movie");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextAutor, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextMovieName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextTime, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonAddTrailer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(125, 125, 125)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)))
                    .addComponent(jLabel10))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextMovieName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jLabelPoster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAddTrailer)
                            .addComponent(jButtonPoster))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonHome)
                            .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jLabelPoster.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosterActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.dir")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getName();
            movie.setMoviePoster(path);
            System.out.println(movie.getMoviePoster());
            jLabelPoster.setIcon(ResizeImage(jLabelPoster,movie.getMoviePoster()));
        }else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("Error");
        }              
    }//GEN-LAST:event_jButtonPosterActionPerformed

    private void jTextMovieNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMovieNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMovieNameActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        Manager manager = new Manager();
        this.setVisible(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        manager.pack();
        manager.setLocationRelativeTo(null);
        manager.setTitle("Home");
        manager.setVisible(true);
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        boolean result = UpdateMovie();
        if(result){
            ImageIcon icon = new ImageIcon(getClass().getResource("/resources/icons/Ok-48.png"));
            JOptionPane.showMessageDialog(this, "Update movie successfully."," Successfull!",JOptionPane.INFORMATION_MESSAGE,icon);
            this.setVisible(false);
            MovieList movieList = new MovieList();
            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            movieList.pack();
            movieList.setLocationRelativeTo(null);
            movieList.setTitle("Movie List");
            movieList.setVisible(true);
        }else{
            ImageIcon icon = new ImageIcon(getClass().getResource("/resources/icons/error.png"));
            JOptionPane.showMessageDialog(this, "Add movie failed."," Warning!",JOptionPane.INFORMATION_MESSAGE,icon);
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonAddTrailerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTrailerActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.dir")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getName();
            movie.setMovieTrailer(path);
            System.out.println(movie.getMovieTrailer());

        }
        else if(result == JFileChooser.CANCEL_OPTION){
            System.out.println("Error");
        }
    }//GEN-LAST:event_jButtonAddTrailerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditMovie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddTrailer;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonPoster;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelPoster;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextAutor;
    private javax.swing.JTextField jTextMovieName;
    private javax.swing.JTextField jTextTime;
    // End of variables declaration//GEN-END:variables
}
