/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movieticketorder.admin;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

import movieticketorder.object.Room;

/**
 *
 * @author Admin
 */
public class SetRoom extends javax.swing.JFrame {

    /**
     * Creates new form SetRoom
     */
    Room room = new Room();
    int matrixSeat[][];
    int seatSum = 0;
    boolean flags = true;
    public SetRoom() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(null);
        this.setTitle("SetUp Room");
    }
    private void matrixSeatInit(int rows, int colums){
        matrixSeat = new int[rows][colums];
        for(int i = 0; i < rows; i++){
            for(int j = 0; j < colums; j++){
                matrixSeat[i][j] = 1;
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextRoomName = new javax.swing.JTextField();
        jTextRows = new javax.swing.JTextField();
        jTextColumns = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonCreateSeat = new javax.swing.JButton();
        jLabelSumSeat = new javax.swing.JLabel();
        jPanelSeat = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonConfirm = new javax.swing.JButton();
        jButtonList = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Room Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NumOf Rows");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NumOf Columns");

        jTextRoomName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextRoomName.setForeground(new java.awt.Color(0, 0, 0));

        jTextRows.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextRows.setForeground(new java.awt.Color(0, 0, 0));

        jTextColumns.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTextColumns.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NumOf Seat: ");

        jButtonCreateSeat.setBackground(new java.awt.Color(153, 255, 153));
        jButtonCreateSeat.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButtonCreateSeat.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCreateSeat.setText("Create Seat");
        jButtonCreateSeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateSeatActionPerformed(evt);
            }
        });

        jLabelSumSeat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabelSumSeat.setForeground(new java.awt.Color(0, 0, 0));

        jPanelSeat.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanelSeatLayout = new javax.swing.GroupLayout(jPanelSeat);
        jPanelSeat.setLayout(jPanelSeatLayout);
        jPanelSeatLayout.setHorizontalGroup(
            jPanelSeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelSeatLayout.setVerticalGroup(
            jPanelSeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jButtonHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/Home-48.png"))); // NOI18N
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/Flat-Red-Square-48.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Empty");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/Flat-Black-Large-Square-48.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Not Use");

        jButtonConfirm.setBackground(new java.awt.Color(153, 255, 153));
        jButtonConfirm.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButtonConfirm.setForeground(new java.awt.Color(0, 0, 0));
        jButtonConfirm.setText("Confirm");
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        jButtonList.setBackground(new java.awt.Color(153, 255, 153));
        jButtonList.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButtonList.setForeground(new java.awt.Color(0, 0, 0));
        jButtonList.setText("Room List");

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelSeat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jButtonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jButtonList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonHome))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextRoomName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSumSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(116, 116, 116)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextColumns, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jTextRows))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonCreateSeat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jButtonCreateSeat))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextColumns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextRoomName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabelSumSeat)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addComponent(jPanelSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonHome)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonList)
                            .addComponent(jButtonConfirm))
                        .addGap(16, 16, 16))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean Confirm_createRoom(int numOfSeat){
        String URL = "jdbc:sqlserver://HiepPC\\SQLEXPRESS:1433;"
                    + "username=sa;password=123456;databasename=movieTicketBooking;encrypt=false";
        boolean flag = true;
        int ID = -1;
        room.setRoomName(jTextRoomName.getText());
        room.setRoomRows(Integer.parseInt(jTextRows.getText()));
        room.setRoomColumns(Integer.parseInt(jTextColumns.getText()));
        room.setNumOfSeat(numOfSeat);
        
        try{
            Connection connect = DriverManager.getConnection(URL);
            String sql = "SELECT TOP 1 roomID FROM room ORDER BY roomID DESC";
            PreparedStatement ps = connect.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                ID = rs.getInt("roomID");
            }
            
            if(ID != 0){
                try{
                    sql = "INSERT INTO room(roomID, roomName, roomRows, roomColumns, roomSeats) "
                                + "VALUES(?,?,?,?,?)";
                    ps = connect.prepareStatement(sql);
                    ps.setInt(1, ++ID);
                    ps.setString(2, room.getRoomName());
                    ps.setInt(3, room.getRoomRows());
                    ps.setInt(4, room.getRoomColumns());
                    ps.setInt(5, numOfSeat);
                    
                    return ps.executeUpdate() > 0;
                }catch(SQLException ex){
                    flag = false;
                    ex.printStackTrace();
                }
            }
        }catch(SQLException ex){
            flag = false;
            ex.printStackTrace();
        }
        
        return flag;
    } 
    public void createMatrix(int rows, int columns){
        seatSum = rows*columns;
        room.setNumOfSeat(seatSum);
        jLabelSumSeat.setText(String.valueOf(seatSum));
        matrixSeatInit(rows, columns);
        JButton btn[] = new JButton[seatSum];
        jPanelSeat.setLayout(new BoxLayout(jPanelSeat, BoxLayout.PAGE_AXIS));
        GridLayout grid = new GridLayout(rows,columns,4,2);
        jPanelSeat.setLayout(grid);
        int buttonWidth = jPanelSeat.getWidth() / columns;
        int buttonHeight = jPanelSeat.getHeight() / rows;
        //int buttonSize = Math.min(jPanelSeat.getWidth() / colums, jPanelSeat.getHeight() / rows);
        for(int i = 0; i < rows; i++){
            for(int j = 0; j < columns; j++){
                int k = 0;
                char nameSeat = 'A';
                if(k < seatSum){
                    btn[k] = new JButton();
                    btn[k].setFont((new Font("Segoe UI", Font.PLAIN, 16)));
                    btn[k].setBackground(Color.RED);
                    btn[k].setPreferredSize(new Dimension(buttonWidth, buttonHeight));
                    btn[k].setText(String.valueOf((char)(nameSeat+i)) + String.valueOf(j+1));
                    btn[k].setForeground(Color.WHITE);
                    final JButton button = btn[k];
                    final int I = i;
                    final int J = j;
                    btn[k].addActionListener(new ActionListener(){
                        private int btnClick = 0;
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            if(btnClick%2 == 0){
                                button.setBackground(Color.BLACK);
                                matrixSeat[I][J] = 0;
                                seatSum--;
                                jLabelSumSeat.setText(String.valueOf(seatSum));
                            }else{
                                button.setBackground(Color.RED);
                                matrixSeat[I][J] = 1;
                                seatSum++;
                                jLabelSumSeat.setText(String.valueOf(seatSum));
                            }
                            btnClick++;
                        }
                    });
                    jPanelSeat.add(btn[k]);
                    k++;
                }
            }
        }
//        revalidate();
//        jPanelSeat.validate();
    }
    private void jButtonCreateSeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateSeatActionPerformed
        // TODO add your handling code here:
        if(jTextRows.getText().isEmpty() || jTextColumns.getText().isEmpty() || jTextRoomName.getText().isEmpty()){
            flags = false;
            ImageIcon icon = new ImageIcon(getClass().getResource("/resources/icons/error-48.png"));
            JOptionPane.showMessageDialog(this, "Don't empty.","ERROR",JOptionPane.INFORMATION_MESSAGE,icon);
        }
        if(flags){
            int rows = Integer.parseInt(jTextRows.getText());
            int colums = Integer.parseInt(jTextColumns.getText());
            createMatrix(rows, colums);
            flags = false;
        }
    }//GEN-LAST:event_jButtonCreateSeatActionPerformed

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        // TODO add your handling code here:
        Manager manager = new Manager();
        this.setVisible(false);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        manager.pack();
        manager.setLocationRelativeTo(null);
        manager.setTitle("Home");
        manager.setVisible(true);
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmActionPerformed
        // TODO add your handling code here:
        boolean result = Confirm_createRoom(seatSum);
         if(result){
            ImageIcon icon = new ImageIcon(getClass().getResource("/resources/icons/Ok-48.png"));
            JOptionPane.showMessageDialog(this, "Add room successfully."," Successfull!",JOptionPane.INFORMATION_MESSAGE,icon);
            this.setVisible(false);
            Manager manager = new Manager();
            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            manager.pack();
            manager.setLocationRelativeTo(null);
            manager.setTitle("Home");
            manager.setVisible(true);
        }else{
            ImageIcon icon = new ImageIcon(getClass().getResource("/resources/icons/error.png"));
            JOptionPane.showMessageDialog(this, "Add movie failed."," Warning!",JOptionPane.INFORMATION_MESSAGE,icon);
        }
    }//GEN-LAST:event_jButtonConfirmActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        flags = true;
        jTextRows.setText("");
        jTextColumns.setText("");
        jPanelSeat.removeAll();
        repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JButton jButtonCreateSeat;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelSumSeat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelSeat;
    private javax.swing.JTextField jTextColumns;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextRoomName;
    private javax.swing.JTextField jTextRows;
    // End of variables declaration//GEN-END:variables
}
